SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_MOVE_SPEED = 300

SHOT_RADIUS = 5
SHOT_SPEED = 500
SHOT_FIRING_RATE = 0.5 # seconds

BUTTON_WIDTH = SCREEN_WIDTH/10
BUTTON_HEIGHT = SCREEN_HEIGHT/15

#Strings
UI_PRE_MENU_TEXT = "Press 'space' to start!"
UI_GAME_OVER_TEXT = "Game Over!"
UI_LEADERBOARD_BUTTON_TEXT = "Leaderboard"
UI_QUIT_BUTTON_TEXT = "Quit"