import pygame


GAME_START_EVENT = pygame.USEREVENT + 1
GAME_OVER_EVENT = pygame.USEREVENT + 2
SCORING_EVENT = pygame.USEREVENT + 3
EVENT_OPEN_MENU = pygame.USEREVENT + 4
EVENT_OPEN_LEADERBOARD = pygame.USEREVENT + 5
